apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          env:
          - name: AUTH_DB_HOST
            value: postgres
          - name: AUTH_DB_USER
            value: kong
          - name: AUTH_KONG_URL
            value: http://apigw:8001
          - name: AUTH_CACHE_HOST
            value: auth-redis
            # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
          - name: AUTH_CACHE_NAME
            value: redis
          - name: DOJOT_MANAGEMENT_USER
            value: auth
          - name: KAFKA_GROUP_ID
            value: auth-group
          image: dojot/auth:v0.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
