apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platiagro

images:
- name: docker.io/platiagro/web-ui
  newTag: 0.2.0-SNAPSHOT

resources:
- deployment.yaml
- service.yaml
- ../overlays/istio/virtual-service.yaml
- ../overlays/application/application.yaml

vars:
- name: platiagro-web-ui-namespace
  objref:
    kind: Service
    name: web-ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: platiagro-web-ui-service
  objref:
    kind: Service
    name: web-ui
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
