apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespace
  - namespace.yaml
  # Istio config
  - destination-rule.yaml
  - service-role-binding.yaml
  # KNative Logger Service
  - knative-service.yaml
  - broker.yaml
  - envoy-filter.yaml
  # Notebook Server
  - ../../notebook/base
  # Datasets API
  - ../../datasets/base
  # Projects API
  - ../../projects/base
  # Web UI
  - ../../web-ui/base
  # Job
  - job.yaml
  #
  - application.yaml
configMapGenerator:
- name: platiagro-install-config
  envs:
  - params.env
vars:
- name: platiagro-app-name
  objref:
    kind: ConfigMap
    name: platiagro-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appName
- name: platiagro-app-version
  objref:
    kind: ConfigMap
    name: platiagro-install-config
    apiVersion: v1
  fieldref:
    fieldpath: data.appVersion
configurations:
- params.yaml
