apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-secrets
  namespace: platiagro
data:
  MINIO_ACCESS_KEY: bWluaW8= # "minio"
  MINIO_SECRET_KEY: bWluaW8xMjM= # "minio123"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minio-secrets
  namespace: anonymous
data:
  MINIO_ACCESS_KEY: bWluaW8= # "minio"
  MINIO_SECRET_KEY: bWluaW8xMjM= # "minio123"
