---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-users
  namespace: dojot
spec:
  template:
    metadata:
      name: postgres-users
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          env:
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_PORT
              value: "5432"
          command:
            - /bin/sh
            - -c
            - "until nc -zv $KONG_PG_HOST $KONG_PG_PORT -w1; do echo 'waiting for db'; sleep 1; done"
      containers:
        - name: postgres-users
          image: dojot/postgres:9.4.24-alpine
          command:
            - sh
            - /opt/postgres-users.sh
          volumeMounts:
            - mountPath: /opt/
              name: postgres-users
      volumes:
        - configMap:
            name: postgres-config-map
          name: postgres-users
      restartPolicy: OnFailure
