apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dojot
configMapGenerator:
- name: ui-parameters
  env: params.env
resources:
- config-map.yaml
- deployment.yaml
- service.yaml
- kong-migration.yaml
vars:
- name: ui-namespace
  objref:
    kind: Service
    name: apigw
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: ui-clusterDomain
  objref:
    kind: ConfigMap
    name: ui-parameters
    version: v1
  fieldref:
    fieldpath: data.uiClusterDomain
- name: service
  objref:
    kind: Service
    name: apigw
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name
