apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
            value: "604800"  # 7 days
          - name: NUM_WORKERS
            value: "2"
