apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: dojot/rabbitmq:3.7-alpine
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5671
          - containerPort: 5672
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rabbitmq
