apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-ui
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    rewrite:
      uri: /
    route:
    - destination:
        host: $(service).$(namespace).svc.$(clusterDomain)
        port:
          number: 80
    timeout: 300s
