apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: projects
spec:
  gateways:
    - kubeflow/kubeflow-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /projects/apis/
      rewrite:
        uri: /
      route:
        - destination:
            host: $(service).$(namespace).svc.$(clusterDomain)
            port:
              number: 8080
      timeout: 300s
