apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: projects
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /projects/apis
    rewrite:
      uri: /projects
    route:
    - destination:
        host: $(service).$(ui-namespace).svc.$(ui-clusterDomain)
        port:
          number: 3000
