apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects
spec:
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
      - name: projects
        env:
        - name: KF_PIPELINES_ENDPOINT
          value: ml-pipeline.kubeflow:8888
        - name: MINIO_ENDPOINT
          value: "minio.platiagro:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secrets
              key: MINIO_SECRET_KEY
        - name: MYSQL_DB_HOST
          value: "mysql.platiagro"
        - name: MYSQL_DB_NAME
          value: "platiagro"
        - name: MYSQL_DB_USER
          value: "root"
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: JUPYTER_ENDPOINT
          value: "http://server.anonymous:80/notebook/anonymous/server"
        - name: KF_PIPELINES_NAMESPACE
          value: anonymous
        - name: SELDON_REST_TIMEOUT
          value: "60000"
        - name: TASK_DEFAULT_MEMORY_REQUEST
          value: 2Gi
        - name: TASK_DEFAULT_CPU_REQUEST
          value: 100m
        - name: TASK_DEFAULT_MEMORY_LIMIT
          value: 10Gi
        - name: TASK_DEFAULT_CPU_LIMIT
          value: 2000m
        - name: TASK_DEFAULT_DEPLOYMENT_IMAGE
          value: $(TASK_DEFAULT_DEPLOYMENT_IMAGE)
        - name: TASK_DEFAULT_EXPERIMENT_IMAGE
          value: $(TASK_DEFAULT_EXPERIMENT_IMAGE)
        - name: TASK_NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: DEPLOYMENT_INIT_TIMEOUT
          value: "300"
        - name: MAIL_USERNAME
          value: ""
        - name: MAIL_PASSWORD
          value: ""
        - name: MAIL_SENDER_ADDRESS
          value: ""
        - name: MAIL_SERVER
          value: ""
        image: docker.io/platiagro/projects:0.2.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      serviceAccountName: platiagro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-agent
spec:
  selector:
    matchLabels:
      app: persistence-agent
  template:
    metadata:
      labels:
        app: persistence-agent
    spec:
      containers:
      - args:
        - --log-level
        - INFO
        name: persistence-agent
        env:
        - name: MYSQL_DB_HOST
          value: "mysql.platiagro"
        - name: MYSQL_DB_NAME
          value: "platiagro"
        - name: MYSQL_DB_USER
          value: "root"
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: KF_PIPELINES_NAMESPACE
          value: anonymous
        image: docker.io/platiagro/persistence-agent:0.2.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
      serviceAccountName: platiagro
