apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platiagro
commonLabels:
  app: mysql

images:
- name: mysql/mysql-server:8.0.3
  newTag: "8.0.3"
  newName: mysql/mysql-server

resources:
- deployment.yaml
- service.yaml
- persistent-volume-claim.yaml
- secret.yaml
