apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: istio-system
        repoRef:
          name: manifests
          path: istio/istio-crds
      name: istio-crds
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: istio-system
        repoRef:
          name: manifests
          path: istio/istio-install
      name: istio-install
    - kustomizeConfig:
        parameters:
          - name: clusterRbacConfig
            value: "OFF"
        repoRef:
          name: manifests
          path: istio/istio
      name: istio
    - kustomizeConfig:
        parameters:
        - name: namespace
          value: istio-system
        repoRef:
          name: manifests
          path: istio/add-anonymous-user-filter
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: application/application-crds
      name: application-crds
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: application/application
      name: application
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: cert-manager
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-crds
      name: cert-manager-crds
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: kube-system
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-kube-system-resources
      name: cert-manager-kube-system-resources
    - kustomizeConfig:
        overlays:
          - self-signed
          - application
        parameters:
          - name: namespace
            value: cert-manager
        repoRef:
          name: manifests
          path: cert-manager/cert-manager
      name: cert-manager
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: metacontroller
      name: metacontroller
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: argo
      name: argo
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kubeflow-roles
      name: kubeflow-roles
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: common/centraldashboard
      name: centraldashboard
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: admission-webhook/bootstrap
      name: bootstrap
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: admission-webhook/webhook
      name: webhook
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: jupyter/jupyter-web-app
      name: jupyter-web-app
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: jupyter/notebook-controller
      name: notebook-controller
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/api-service
      name: api-service
    - kustomizeConfig:
        overlays:
          - application
        parameters:
          - name: minioPvcName
            value: minio-pv-claim
        repoRef:
          name: manifests
          path: pipeline/minio
      name: minio
    - kustomizeConfig:
        overlays:
          - application
        parameters:
          - name: mysqlPvcName
            value: mysql-pv-claim
        repoRef:
          name: manifests
          path: pipeline/mysql
      name: mysql
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/persistent-agent
      name: persistent-agent
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-runner
      name: pipelines-runner
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-ui
      name: pipelines-ui
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-viewer
      name: pipelines-viewer
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/scheduledworkflow
      name: scheduledworkflow
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipeline-visualization-service
      name: pipeline-visualization-service
    - kustomizeConfig:
        overlays:
          - application
          - istio
        parameters:
          - name: admin
            value: anonymous@kubeflow.org
        repoRef:
          name: manifests
          path: profiles
      name: profiles
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: seldon/seldon-core-operator
      name: seldon-core-operator
    - kustomizeConfig:
        parameters:
          - name: user
            value: anonymous@kubeflow.org
          - name: profile-name
            value: anonymous
        repoRef:
          name: manifests
          path: default-install
      name: default-install
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: anonymous
          - name: memory-limits
            value: 4G
          - name: cpu-limits
            value: "2"
        repoRef:
          name: manifests
          path: platiagro/notebook
      name: notebook
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: platiagro
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/namespace
      name: namespace
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: platiagro
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/datasets
      name: datasets
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: platiagro
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/pipelines
      name: pipelines
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: platiagro
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/projects
      name: projects
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: platiagro
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/web-ui
      name: web-ui
  repos:
    - name: manifests
      uri: https://github.com/platiagro/manifests/archive/v0.2.0-kubeflow-v1.1-branch.tar.gz
  version: v0.2.0
