apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  namespace: kubeflow
spec:
  applications:
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: istio-system
        repoRef:
          name: manifests
          path: istio/istio-crds
      name: istio-crds
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: istio-system
        repoRef:
          name: manifests
          path: istio/istio-install
      name: istio-install
    - kustomizeConfig:
        overlays:
          - https-gateway
        parameters:
          - name: clusterRbacConfig
            value: "OFF"
        repoRef:
          name: manifests
          path: istio/istio
      name: istio
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: application/application-crds
      name: application-crds
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: application/application
      name: application
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: cert-manager
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-crds
      name: cert-manager-crds
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: kube-system
        repoRef:
          name: manifests
          path: cert-manager/cert-manager-kube-system-resources
      name: cert-manager-kube-system-resources
    - kustomizeConfig:
        overlays:
          - self-signed
          - application
        parameters:
          - name: namespace
            value: cert-manager
        repoRef:
          name: manifests
          path: cert-manager/cert-manager
      name: cert-manager
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: istio-system
        repoRef:
          name: manifests
          path: istio/ingressgateway-self-signed-cert
      name: ingressgateway-self-signed-cert
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: metacontroller
      name: metacontroller
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: argo
      name: argo
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: kubeflow-roles
      name: kubeflow-roles
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: common/centraldashboard
      name: centraldashboard
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: admission-webhook/bootstrap
      name: bootstrap
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: admission-webhook/webhook
      name: webhook
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: jupyter/jupyter-web-app
      name: jupyter-web-app
    - kustomizeConfig:
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: jupyter/notebook-controller
      name: notebook-controller
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/api-service
      name: api-service
    - kustomizeConfig:
        overlays:
          - application
        parameters:
          - name: minioPvcName
            value: minio-pv-claim
        repoRef:
          name: manifests
          path: pipeline/minio
      name: minio
    - kustomizeConfig:
        overlays:
          - application
        parameters:
          - name: mysqlPvcName
            value: mysql-pv-claim
        repoRef:
          name: manifests
          path: pipeline/mysql
      name: mysql
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/persistent-agent
      name: persistent-agent
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-runner
      name: pipelines-runner
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - istio
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-ui
      name: pipelines-ui
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipelines-viewer
      name: pipelines-viewer
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/scheduledworkflow
      name: scheduledworkflow
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: deployments
        overlays:
          - application
        repoRef:
          name: manifests
          path: pipeline/pipeline-visualization-service
      name: pipeline-visualization-service
    - kustomizeConfig:
        overlays:
          - application
          - istio
        parameters:
          - name: admin
            value: johnDoe@acme.com
        repoRef:
          name: manifests
          path: profiles
      name: profiles
    - kustomizeConfig:
        overlays:
          - application
        repoRef:
          name: manifests
          path: seldon/seldon-core-operator
      name: seldon-core-operator
    - kustomizeConfig:
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/datasets
      name: datasets
    - kustomizeConfig:
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/pipelines
      name: pipelines
    - kustomizeConfig:
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/projects
      name: projects
    - kustomizeConfig:
        overlays:
          - istio
        repoRef:
          name: manifests
          path: platiagro/web-ui
      name: web-ui
    - kustomizeConfig:
        overlays:
          - istio
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/apigw
      name: apigw
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/auth
      name: auth
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/auth-redis
      name: auth-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/backstage
      name: backstage
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/cron
      name: cron
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/data-broker
      name: data-broker
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/data-broker-redis
      name: data-broker-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/data-manager
      name: data-manager
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/device-manager
      name: device-manager
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/device-manager-redis
      name: device-manager-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/ejbca
      name: ejbca
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/flowbroker
      name: flowbroker
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/flowbroker-context-manager
      name: flowbroker-context-manager
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/flowbroker-redis
      name: flowbroker-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/flowbroker-redis
      name: flowbroker-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/gui
      name: gui
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/history
      name: history
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/image-manager
      name: image-manager
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/iotagent-lwm2m
      name: iotagent-lwm2m
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/iotagent-mqtt
      name: iotagent-mqtt
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/kafka
      name: kafka
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/minio
      name: minio-dojot
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/mongodb
      name: mongodb
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/mosca-redis
      name: mosca-redis
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/persister
      name: persister
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/postgres
      name: postgres
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/rabbitmq
      name: rabbitmq
    - kustomizeConfig:
        parameters:
          - name: namespace
            value: dojot
        repoRef:
          name: manifests
          path: dojot/zookeeper
      name: zookeeper
  repos:
    - name: manifests
      uri: https://github.com/platiagro/manifests/archive/feature/dojot-installer.tar.gz
  version: v0.4.3
