apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ingress-crt
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  domains:
  - example.org
  commonName: "istio-ingressgateway-root-ca"
  isCA: true
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
