apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datasets
  name: datasets
spec:
  selector:
    matchLabels:
      app: datasets
  template:
    metadata:
      labels:
        app: datasets
    spec:
      containers:
      - name: datasets
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service.kubeflow:9000"
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: docker.io/platiagro/datasets:0.2.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
