apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: dojot/zookeeper:3.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /logs
            name: logs
          - mountPath: /datalog
            name: datalog
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-data
      - name: logs
        persistentVolumeClaim:
          claimName: zookeeper-logs
      - name: datalog
        persistentVolumeClaim:
          claimName: zookeeper-datalog
