apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-tasks
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-experiments
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
