apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  labels:
    app: server
    add-nvidia-visible-devices: "true"
  name: server
  namespace: anonymous
spec:
  template:
    spec:
      initContainers:
      - image: busybox
        arguments: ["mkdir", "-p", "/home/jovyan/tasks"]
        name: busybox
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace-server
      containers:
      - image: "$(image)"
        env:
        - name: EXPERIMENT_ID
          value: notebook
        - name: OPERATOR_ID
          value: notebook
        name: server
        resources:
          requests:
            cpu: 100m
            memory: 2G
          limits:
            cpu: "$(cpu-limits)"
            memory: "$(memory-limits)"
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace-server
      serviceAccountName: default-editor
      ttlSecondsAfterFinished: 300
      volumes:
      - name: workspace-server
        persistentVolumeClaim:
          claimName: workspace-server
