apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platiagro
commonLabels:
  app: mysql

images:
- name: mysql
  newTag: '8.0.3'
  newName: mysql

resources:
- deployment.yaml
- service.yaml
- persistent-volume-claim.yaml

configMapGenerator:
- name: pipeline-mysql-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: mysqlPvcName
  objref:
    kind: ConfigMap
    name: pipeline-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlPvcName
configurations:
- params.yaml
