apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: platiagro
  name: platiagro
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machinelearning.seldon.io
  resources:
  - seldondeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - get
  - list
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - '*'
