---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: platiagro
  name: platiagro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platiagro
subjects:
- kind: ServiceAccount
  name: platiagro
  namespace: platiagro
- kind: ServiceAccount
  name: default-editor
  namespace: anonymous
