apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platiagro

images:
- name: docker.io/platiagro/web-ui
  newTag: 0.2.0-SNAPSHOT

resources:
- deployment.yaml
- service.yaml

images:
- name: docker.io/platiagro/web-ui
  newName: docker.io/platiagro/web-ui
  newTag: 0.2.0-SNAPSHOT
