apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: 9104
    spec:
      containers:
      - name: mysql
        args:
        - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      - name: mysql-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "root@(mysql:3306)/"
        image: prom/mysqld-exporter
        ports:
        - containerPort: 9104
          name: http
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: $(mysqlPvcName)
