apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pipelines
spec:
  selector:
    matchLabels:
      app: pipelines
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      containers:
        - image: platiagro/pipelines:0.2.0-SNAPSHOT
          name: pipelines
          env:
            - name: KF_PIPELINES_ENDPOINT
              value: ml-pipeline.deployments:8888
            - name: MINIO_ENDPOINT
              value: "minio-service.kubeflow:9000"
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
            - name: MYSQL_DB_HOST
              value: "mysql.kubeflow"
            - name: MYSQL_DB_NAME
              value: "platiagro"
            - name: JUPYTER_ENDPOINT
              value: "http://server.anonymous:80/notebook/anonymous/server"
            - name: KF_PIPELINES_NAMESPACE
              value: deployments
            - name: MEMORY_REQUEST
              value: 2G
            - name: CPU_REQUEST
              value: 100m
            - name: MEMORY_LIMIT
              value: 10G
            - name: CPU_LIMIT
              value: 2000m
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      serviceAccountName: pipelines
